language: java

jdk:
  - openjdk11

node_js:
  - 18.17.1

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.npm
    - $HOME/.yarn-cache

before_install:
  - npm install -g yarn  
  - curl -sLo gradle.zip https://services.gradle.org/distributions/gradle-7.6-bin.zip && unzip gradle.zip -d /tmp && export GRADLE_HOME=/tmp/gradle-7.6 && export PATH=$GRADLE_HOME/bin:$PATH

install:
  - ./gradlew runYarnInstall
  - ./gradlew runYarnInstallFrontEnd

script:
  - ./gradlew runDatabase
  - ./gradlew executeDatabase
  - ./gradlew runBuild
  - ./gradlew runUnleash